### ISSUE TITLE
Import Bitwarden TOTP as pass-otp format

### ISSUE THREAD

**Issue by Limero** [roddhjav/pass-import#126]
I just imported my whole Bitwarden vault with pass-import and I noticed that the Authenticator Key (TOTP) stored will not work right away with pass-otp.

Is there any way to make each login work right away when imported, without manually adding `otpauth://totp/totp-secret?secret=AAAAAAAAAAAAAAAA&issuer=totp-secret` around each secret?

**Comment by roddhjav** [comment]
The otp import from bitwarden (and other similar pm) is not very polished. I will have a look a it once I get the time.

**Comment by roddhjav** [comment]
Fixed by #157

**Comment by Stunt0265** [comment]
Was this ever resolved?  When I import my Bitwarden json file, the OTP secret still doesn't have the proper formatting.

**Comment by Stunt0265** [comment]
I found that some of mine stored in Bitwarden are in the correct format, but most are just the raw OTP secret.
