### ISSUE TITLE
Import of keepassxc fails (2)

### ISSUE THREAD

**Issue by pietrotavares** [roddhjav/pass-import#161]
**UPDATE:**
**The [keepass2csv2pass.py script](https://git.zx2c4.com/password-store/tree/contrib/importers/keepass2csv2pass.py) did it for me.**

I'm having the same issue described in #90 
My database has compression enabled, therefore it should work [(I presume..)](https://github.com/roddhjav/pass-import/issues/90#issuecomment-552227947).

However, when I try to `pass import keepassxc passwords.kbdx` I get the following error:
```
sequence item 1: expected str instance, NoneType found
Error: passwords.kbdx is not a valid exported keepassxc file.
```

I've also tried to import from a csv file with `pass import keepassxc passwords.csv`.
First, it prompts with "Password for passwords.csv:" (?)
Then, no matter what I type in, it fails with the following error:
```
'NoneType' object has no attribute 'payload'
Error: passwords.csv is not a valid exported keepassxc file.
```

I'm on Debian 10 (4.19.0-17-amd64) running Python 3.7.3.

Thank you.

**Comment by roddhjav** [comment]
That can be different things, can you provide the output with the `-vvv` option used: `pass import keepassxc passwords.kbdx -vvv`
You can also try directly: `pass import passwords.kbdx -vvv`

**Comment by pietrotavares** [comment]
**UPDATE: [keepass2csv2pass.py](https://git.zx2c4.com/password-store/tree/contrib/importers/keepass2csv2pass.py) worked for me.**

Both `pass import passwords.kbdx -vvv` and `pass import keepassxc passwords.kbdx -vvv` yield this same error:
```
.  Trying to guess file format and manager name.
.  Importer: keepassxc, Format: kdbx, Version:
.  Importing passwords from KeepassxcKDBX to PasswordStore
Password for passwords.kbdx:
.  Traceback (most recent call last):
File "/home/pietro/.local/lib/python3.7/site-packages/pass_import/__main__.py", line 342, in pass_import
  importer.parse()
File "/home/pietro/.local/lib/python3.7/site-packages/pass_import/formats/kdbx.py", line 138, in parse
  history = self._getentry(hentry)
File "/home/pietro/.local/lib/python3.7/site-packages/pass_import/formats/kdbx.py", line 56, in _getentry
  entry['group'] = os.sep.join(kpentry.path)
TypeError: sequence item 1: expected str instance, NoneType found

sequence item 1: expected str instance, NoneType found
Error: passwords.kbdx is not a valid exported keepassxc file.
```

Looks like a parsing error for deep-nested groups? (btw: the group names are [a-z][A-Z] strings, no whitespaces or slashes).

**Comment by roddhjav** [comment]
Ok, that was a bug. It should be fixed with 2231afe.

**Comment by pietrotavares** [comment]
I'm still seeing the issue in the latest version.

What I did:
1. `pip uninstall pass-import`
3. `git clone https://github.com/roddhjav/pass-import`
4. `cd pass-import`
5. `python3 setup.py install --user`
6.
```
pass import passwords.kbdx -vvv
pass import keepassxc passwords.kbdx -vvv
./import.bash ~/Backups/passwords.kbdx -vvv
```

All yielding the same error as before, i.e.,
```
.  Trying to guess file format and manager name.
.  Importer: keepassxc, Format: kdbx, Version:
.  Importing passwords from KeepassxcKDBX to PasswordStore
Password for passwords.kbdx:
.  Traceback (most recent call last):
File "/home/pietro/.local/lib/python3.7/site-packages/pass_import/__main__.py", line 342, in pass_import
  importer.parse()
File "/home/pietro/.local/lib/python3.7/site-packages/pass_import/formats/kdbx.py", line 139, in parse
  history = self._getentry(hentry)
File "/home/pietro/.local/lib/python3.7/site-packages/pass_import/formats/kdbx.py", line 57, in _getentry
  entry['group'] = os.sep.join(kpentry.path)
TypeError: sequence item 1: expected str instance, NoneType found

sequence item 1: expected str instance, NoneType found
Error: passwords.kbdx is not a valid exported keepassxc file.
```

**Comment by amorphous** [comment]
I'm having the same problem - using a build from the master branch. I get this when trying to import a keepassx file:
```
$ pass import keepassx  '~/Documents/KeyPass Dec 2021.kdbx' -vvv

  .  Trying to guess file format.
  .  Importer: keepassx, Format: xml, Version: 
  .  Importing passwords from KeepassxXML to PasswordStore
  .  Traceback (most recent call last):
  File "~/.local/lib/python3.9/site-packages/pass_import-3.2-py3.9.egg/pass_import/__main__.py", line 341, in pass_import
    with cls_import(conf['in'], settings=settings) as importer:
  File "~/.local/lib/python3.9/site-packages/pass_import-3.2-py3.9.egg/pass_import/core.py", line 113, in __enter__
    raise PMError("%s is not a password repository." % self.prefix)
pass_import.errors.PMError: ~/Documents/KeyPass Dec 2021.kdbx is not a password repository.

```
```
$ pass import keepassx  '~/Documents/key.csv' -vvv
  .  Trying to guess file format.
  .  Importer: keepassx, Format: xml, Version: 
  .  Importing passwords from KeepassxXML to PasswordStore
  .  Traceback (most recent call last):
  File "~/.local/lib/python3.9/site-packages/pass_import-3.2-py3.9.egg/pass_import/__main__.py", line 341, in pass_import
    with cls_import(conf['in'], settings=settings) as importer:
  File "~/.local/lib/python3.9/site-packages/pass_import-3.2-py3.9.egg/pass_import/core.py", line 113, in __enter__
    raise PMError("%s is not a password repository." % self.prefix)
pass_import.errors.PMError: ~/Documents/key.csv is not a password repository.

```
I've also tried importing using  keepassxc and keepassx2 against the keepassx file.

Should I be expecting a request for a passowrd?

**Comment by roddhjav** [comment]
That is different. According to [the code](https://github.com/roddhjav/pass-import/blob/master/pass_import/core.py#L103) your path `~/Documents/KeyPass Dec 2021.kdbx` does not exist.

**Comment by zeorin** [comment]
Also not working for me:
```

**Comment by roddhjav** [comment]
This has already been fixed with  2231afe. Use the master branch. I will release a new version soon anyway.

**Comment by roddhjav** [comment]
That obviously an issue for pykeepass, pass import will manage it anyway. Should be fixed in a68d947.
